version: '3.9'

services:
  intelpou_nestapp:
    container_name: intelpou_nestapp
    image: intelpou/intelpou_nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - POSTGRES_HOST=27.74.250.199
      - POSTGRES_USER=surbana
      - POSTGRES_PASSWORD=EIyXORyBB6ZrB8U
      - POSTGRES_DATABASE=surbana_db
      - POSTGRES_PORT=25432
